all:	q1aa	q1ab	q1ba	q1bb

q1aa:
	gcc -w -o ./a/q1aa ./a/i.c
q1ab:
	gcc -w -o ./a/q1ab ./a/ii.c
q1ba:
	gcc -w -o ./b/q1ba ./b/i.c
q1bb:
	gcc -w -o ./b/q1bb ./b/ii.c

clean:
	rm ./a/q1aa ./a/q1ab
	rm ./b/q1ba ./b/q1bb