all:	p1f	p2f	p1s	p2s	p1shm	p2shm

p1f:
	gcc -w -o ./q2/fifo/p1f ./q2/fifo/p1.c
p2f:
	gcc -w -o ./q2/fifo/p2f ./q2/fifo/p2.c
p1s:
	gcc -w -o ./q2/sockets/p1s ./q2/sockets/p1.c
p2s:
	gcc -w -o ./q2/sockets/p2s ./q2/sockets/p2.c
p1shm:
	gcc -w -o ./q2/shared_mem/p1shm ./q2/shared_mem/p1.c
p2shm:
	gcc -w -o ./q2/shared_mem/p2shm ./q2/shared_mem/p2.c